stages:
  - build
  - test

build_car:
  image: alpine
  stage: build
  script:
    - echo "Building the car"
    - mkdir build
    - cd build
    - echo "chassis" >> car.txt
    - echo "engine" >> car.txt
    - echo "wheels" >> car.txt
    - cat car.txt
  artifacts:
    paths:
      - build/

test_car:
  image: alpine
  stage: test
  script:
    - test -f build/car.txt # test if the file exists
    - grep "chassis" build/car.txt
    - grep "engine" build/car.txt
    - grep "wheels" build/car.txt
